### ISSUE TITLE
Backend to serve active tournaments list

### ISSUE THREAD

**Issue by michal-k** [michal-k/SnailBucket2#30]
Expected output:
[
   {
     'id': 'foo',
     'name': 'Snail Bucket Monthly 2015',
     'rounds': ['1'],
     'signup': false
    },
    {
      'id': 'frf',
      'name': 'Snail Bucket 4',
      'rounds': [],
      'signup': true
    }
];

Let's assume that active tournaments are:
- tournaments finished within the last 30 days
- tournaments accepting sign ups
- tournaments actually played

If no tournaments would be returned using the criteria above, the most recently played tournament should be returned.

@mooskagh Interested in doing that?

**Comment by mooskagh** [comment]
Will do.
Also is there a bug for registration of users? Will also implement that.
