### ISSUE TITLE
Impossible not to set result when adding a game in admin

### ISSUE THREAD

**Issue by michal-k** [michal-k/SnailBucket2#43]

**Comment by mooskagh** [comment]
Originally I though that game should always have a status, even when it's not played. (TL has '-' for not schdeduled [default], '+' for pending, '*' for games in progress and 'AJD' for adjourned games).

Not sure that it's needed for snailbucket, so will enumerate possible results of finished game, and all non-played games will have it NULL.

**Comment by michal-k** [comment]
This would be ok, we can do as you suggest, if you prefer. I have no
preferences.

niedz., 1.05.2016 o 17:20 użytkownik mooskagh notifications@github.com
napisał:
